
try {
    throw 'error!';
}
catch (e) {
    console.log('error');
}

const a = 'hard';

throw `a ${a} error!`

throw a + '!';
